use aurionpro;
insert into category set `category` = 'Requirment from State';
insert into category set `category` = 'Master upload related cases';
insert into category set `category` = 'CCE app issue';
insert into category set `category` = 'Technical issue';
insert into category set `category` = 'Installation/Configuration';
insert into category set `category` = 'General inquiry';
insert into category set `category` = 'Feature request';
insert into category set `category` = 'Product feedback';
select * from category;